openapi: 3.0.2
info:
  title: "Rating"
  version: 1.0.0
  description: This is a simple Rating microservice API by team 3
paths:
  /rating:
    post:
      tags:
        - "Rating"
      summary: "Rate post"
      description: "Rate / edit a post"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                collectionId:
                  type: "integer"
                  format: "int64"
                postID:
                  type: "integer"
                  format: "int64"
                userID:
                  type: "integer"
                  format: "int64"
                rating:
                  type: "object"
                  properties:
                    criterion:  
                      type: "array"
                      items:
                        format: "int64"
                token:
                  type: "string"
            example:
              collectionId: "216599"
              postID: "46161651"
              userID: "789816"
              rating: {"Качество" : 5, "Цена" : 3, "Внешний вид" : 4}
              token: "ff48d4fv64d45df1v41db781t7g"
      responses:
        200:
          description: "OK"
        403:
          description: "Not enough rights"
          
  /rating/collections/{collectionID}/posts/{postID}/users/{userID}/criterion/{criterion}:
   get:
      tags: 
        - "Rating"
      summary: "Get post rating of user by criterion"
      description: "Getting a post rating from a user by criterion"
      parameters:
      - name: "collectionID"
        in: "path"
        description: "ID collection"
        required: true
        schema:
          type: "integer"
          format: "int64"
      - name: "postID"
        in: "path"
        description: "ID post"
        required: true
        schema:
          type: "integer"
          format: "int64"
      - name: "criterion"
        in: "path"
        description: "Name of the criterion"
        required: true
        schema:
          type: "string"
      - name: "userID"
        in: "path"
        description: "User ID"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  criterion:
                    type: "integer"
                    format: "int64"
              example:
                "Цена" : 7
        404:
          description: "Error"
          
  /rating/avarage/collection/{collectionID}/posts/{postID}/criterion/{criterion}:
    get:
      tags: 
        - "Rating"
      summary: "Get average post rating by criterion"
      description: ""
      parameters:
      - name: "collectionID"
        in: "path"
        description: "ID collection"
        required: true
        schema:
          type: "integer"
          format: "int64"
      - name: "postID"
        in: "path"
        description: "ID post"
        required: true
        schema:
          type: "integer"
          format: "int64"
      - name: "criterion"
        in: "path"
        description: "Name of the criterion"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  criterion:
                    type: "integer"
                    format: "int64"
              example:
                "Цена" : 7
        404:
          description: "Error"
  
  /rating/average/collections/{collectionID}/posts/{postID}:
    get:
      tags: 
        - "Rating"
      summary: "Get average post rating"
      description: "The average post rating is the average of the average ratings for the criteria"
      parameters:
      - name: "collectionID"
        in: "path"
        description: "ID collection"
        required: true
        schema:
          type: "integer"
          format: "int64"
      - name: "postID"
        in: "path"
        description: "ID post"
        required: true
        schema:
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  estimation:
                    type: "integer"
                    format: "int64"
              example:
                "postRating" : 7
        404:
          description: "Error"